export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_ERROR = "FETCH_ARTICLES_ERROR";
export const INFINITE_LOADING_START = "INFINITE_LOADING_START";

export const LOGIN_ERROR = "LOGIN_ERROR";

export const USER_LOGIN = "USER_LOGIN";
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_LOGOUT = "USER_LOGOUT";

export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const ENABLE_HEADER_STICKY = "ENABLE_HEADER_STICKY";
export const DISABLE_HEADER_STICKY = "DISABLE_HEADER_STICKY";
